# super level permission required
sudo: required
language: generic 
services: 
  - docker
# before deploying/run tests
before_install: 
  - docker build -t aartibhagtani/docker_image -f ./frontend/Dockerfile.dev ./frontend
script:
  - docker run -e CI=true aartibhagtani/docker_image npm run test
deploy:
  # travis ci comes with some cloud services like aws, gcp, digital ocean 
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker_image"
  env: "DockerImage-env"
  bucket_name: elasticbeanstalk-eu-west-1-338115957636
  bucket_path: "docker_image"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  